// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20160120.e0795bdfe9ac8e034e0328b8d09557d34552f799 2016-01-20T19:02:42Z

#include "ccnxPortal_About.h"

const char *ccnxPortal_What = "@(#)CCNx Portal API 1.0.20160105.eedfc5903509513a0a5cee650d84b33655ad358c 2016-01-20T19:03:45.777531\n@(#)\tCopyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\n@(#)\tAll rights reserved.";

const char *
ccnxPortalAbout_Name(void)
{
    return "CCNx Portal API";
}

const char *
ccnxPortalAbout_Version(void)
{
    return "1.0.20160105.eedfc5903509513a0a5cee650d84b33655ad358c";
}

const char *
ccnxPortalAbout_About(void)
{
    return "CCNx Portal API 1.0.20160105.eedfc5903509513a0a5cee650d84b33655ad358c 2016-01-20T19:03:45.777531\nCopyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n";
}

const char *
ccnxPortalAbout_MiniNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n";
}

const char *
ccnxPortalAbout_ShortNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above copyright\n      notice, this list of conditions and the following disclaimer in the\n      documentation and/or other materials provided with the distribution.\n    * Patent rights are not granted under this agreement. Patent rights are\n      available under FRAND terms.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL XEROX or PARC BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n";
}

const char *
ccnxPortalAbout_LongNotice(void)
{
    return "Copyright (c) 2016, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)\nAll rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above copyright\n      notice, this list of conditions and the following disclaimer in the\n      documentation and/or other materials provided with the distribution.\n    * Patent rights are not granted under this agreement. Patent rights are\n      available under FRAND terms.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND\nANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL XEROX or PARC BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n";
}

