// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20160120.e0795bdfe9ac8e034e0328b8d09557d34552f799 2016-01-20T19:02:42Z

#ifndef ccnxPortal_About_h
#define ccnxPortal_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *ccnxPortal_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *ccnxPortalAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *ccnxPortalAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *ccnxPortalAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *ccnxPortalAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *ccnxPortalAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *ccnxPortalAbout_LongNotice(void);

#endif // ccnxPortal_About_h
